#pragma once

// controllerAxesCodes from glfw3.h
#define CE_CONTROLLER_AXIS_LEFT_X        0
#define CE_CONTROLLER_AXIS_LEFT_Y        1
#define CE_CONTROLLER_AXIS_RIGHT_X       2
#define CE_CONTROLLER_AXIS_RIGHT_Y       3
#define CE_CONTROLLER_AXIS_LEFT_TRIGGER  4
#define CE_CONTROLLER_AXIS_RIGHT_TRIGGER 5
#define CE_CONTROLLER_AXIS_LAST          CE_CONTROLLER_AXIS_RIGHT_TRIGGER

// controllerButtonsCodes from glfw3.h
#define CE_CONTROLLER_BUTTON_A               0
#define CE_CONTROLLER_BUTTON_B               1
#define CE_CONTROLLER_BUTTON_X               2
#define CE_CONTROLLER_BUTTON_Y               3
#define CE_CONTROLLER_BUTTON_LEFT_BUMPER     4
#define CE_CONTROLLER_BUTTON_RIGHT_BUMPER    5
#define CE_CONTROLLER_BUTTON_BACK            6
#define CE_CONTROLLER_BUTTON_START           7
#define CE_CONTROLLER_BUTTON_GUIDE           8
#define CE_CONTROLLER_BUTTON_LEFT_THUMB      9
#define CE_CONTROLLER_BUTTON_RIGHT_THUMB     10
#define CE_CONTROLLER_BUTTON_DPAD_UP         11
#define CE_CONTROLLER_BUTTON_DPAD_RIGHT      12
#define CE_CONTROLLER_BUTTON_DPAD_DOWN       13
#define CE_CONTROLLER_BUTTON_DPAD_LEFT       14
#define CE_CONTROLLER_BUTTON_LAST            CE_CONTROLLER_BUTTON_DPAD_LEFT